// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://voltxeyxpnzehsyxiafv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvbHR4ZXl4cG56ZWhzeXhpYWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NzE5MzAsImV4cCI6MjA1NTQ0NzkzMH0.TArV95DzP8XAJeeF_vnpywlcexI0nYMqACbSwhGgn8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);